apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-login
  namespace: was
  annotations:
    kubernetes.io/change-cause: was:v1.0
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: was-login
  template:
    metadata:
      labels:
        app: was-login
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - was-login
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: was-login
      containers:
        - image: ysryu/tomcat-main:v1.0
          name: was-login
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /login.jsp
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /login.jsp
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/local/tomcat/webapps/ROOT/
      volumes:
        - name: persistent-storage # 볼륨이름
          persistentVolumeClaim:
            claimName: pvc-was-login # PVC를 참조
