apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was-login
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-was-login
  nfs:
    path: /dynamic_provisioning/login
    server: fs-05f0e46aec263fa2a.efs.ap-northeast-2.amazonaws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was-main
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-was-main
  nfs:
    path: /dynamic_provisioning/main
    server: fs-05f0e46aec263fa2a.efs.ap-northeast-2.amazonaws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was-order
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-was-order
  nfs:
    path: /dynamic_provisioning/order
    server: fs-05f0e46aec263fa2a.efs.ap-northeast-2.amazonaws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was-reservation
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-was-reservation
  nfs:
    path: /dynamic_provisioning/reservation
    server: fs-05f0e46aec263fa2a.efs.ap-northeast-2.amazonaws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was-signup
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-was-signup
  nfs:
    path: /dynamic_provisioning/signup
    server: fs-05f0e46aec263fa2a.efs.ap-northeast-2.amazonaws.com
